server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /haha
    username: mq
    password: 123456
    host: 127.0.0.1

leyou:
  sms:
    accessKeyId: LTAI196Huj2cCYqr
    accessKeySecret: 4TP1rYJuBvGcAFcws0W0FJ0c9oUqkV
    signName: 短信验证
    verifyCodeTemplate: SMS_13540085
